export const ERROR_CODES = {
  COMMON_VALIDATION_FAILED: "COMMON_VALIDATION_FAILED",
  COMMON_UNAUTHORIZED: "COMMON_UNAUTHORIZED",
  COMMON_FORBIDDEN: "COMMON_FORBIDDEN",
  COMMON_NOT_FOUND: "COMMON_NOT_FOUND",
  COMMON_CONFLICT: "COMMON_CONFLICT",
  COMMON_RATE_LIMITED: "COMMON_RATE_LIMITED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_TYPE_MISMATCH: "AUTH_USER_TYPE_MISMATCH",
  AUTH_EMAIL_DUPLICATED: "AUTH_EMAIL_DUPLICATED",
  AUTH_EMAIL_CODE_INVALID: "AUTH_EMAIL_CODE_INVALID",
  FILE_INVALID_TYPE: "FILE_INVALID_TYPE",
  FILE_SIZE_EXCEEDED: "FILE_SIZE_EXCEEDED",
  APPLICATION_ALREADY_SUBMITTED: "APPLICATION_ALREADY_SUBMITTED",
  INTERVIEW_SESSION_EXPIRED: "INTERVIEW_SESSION_EXPIRED",
  DEVICE_PERMISSION_DENIED: "DEVICE_PERMISSION_DENIED",
  AI_PROCESS_FAILED: "AI_PROCESS_FAILED",
  AI_GUARDRAIL_BLOCKED: "AI_GUARDRAIL_BLOCKED",
  REPORT_NOT_READY: "REPORT_NOT_READY",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
